### ISSUE TITLE
Sticky menu on scroll navigation template

### ISSUE THREAD

**Issue by rkiesler1** [mashery/blackbeard#112]
e.g., http://developer.lowes.com

**Comment by cferdinandi** [comment]
Since this is implemented with CSS, and will vary based on the theme, this strikes me as something best implemented on a case-by-case basis.

It requires adding a bit of padding to the body, and that will vary by type choice, font size, and a bunch of other things you might to do to the header, so there's no good way to reliably roll out the same solution for all use cases.
